#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
    echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- \033[1;33mnecesitas ejecutar como root\033[0m"
    rm $HOME/Plus >/dev/null 2>&1
    exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r' | sed -e 's/[^a-z.]//ig' | rev)
_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×' | sed -e 's/[^a-z/]//ig')
_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×' | sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} -y >/dev/null 2>&1
        ${comando[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m[" # Translated "AGUARDE" to "ESPERE"
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m[" # Translated "AGUARDE" to "ESPERE"
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m" # "OK !" is universal, no translation needed
    tput cnorm
}
function verif_key() {
    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
    chmod +x $_Ink/list >/dev/null 2>&1
    [[ ! -e "$_Ink/list" ]] && {
        echo -e "\n\033[1;31m¡CLAVE INVÁLIDA!\033[0m" # Translated "KEY INVÁLIDA!" to "¡CLAVE INVÁLIDA!"
        rm -rf $HOME/Plus >/dev/null 2>&1
        sleep 2
        clear
        exit 1
    }
}
function verif_key2() {
    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
    chmod +x $_Ink/listARM >/dev/null 2>&1
    [[ ! -e "$_Ink/listARM" ]] && {
        echo -e "\n\033[1;31m¡CLAVE INVÁLIDA!\033[0m" # Translated "KEY INVÁLIDA!" to "¡CLAVE INVÁLIDA!"
        rm -rf $HOME/Plus >/dev/null 2>&1
        sleep 2
        clear
        exit 1
    }
}

otimize_python() {
    # INSTALA PYTHON AO PYTHON2 - No user text, technical comment
    apt-get install python -y >/dev/null 2>&1
    apt-get install python2 -y >/dev/null 2>&1
    # INSTALA PYTHON3.6 AO PYTHON3.9 - No user text, technical comment
    apt-get install python3.6 -y >/dev/null 2>&1
    apt-get install python3.7 -y >/dev/null 2>&1
    apt-get install python3.8 -y >/dev/null 2>&1
    apt-get install python3.9 -y >/dev/null 2>&1
    # CRIA ALTERNATIVAS PYTHON - No user text, technical comment
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 >/dev/null 2>&1
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 3 >/dev/null 2>&1
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2 >/dev/null 2>&1
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 4 >/dev/null 2>&1
    # INSTALA PIP - No user text, technical comment
    apt install pip -y
    apt install python3-pip -y
    # INSTALA SOCAT - No user text, technical comment
    apt install socat -y
    #SETAR PYTHON3 - No user text, technical comment
    update-alternatives --set python3 /usr/bin/python3.6
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7
tput setab 4
tput bold
printf '%40s%s%-12s\n' "BIENVENIDO A SSHPLUS MANAGER" # Translated "BEM VINDO AO SSHPLUS MANAGER"
tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "             \033[1;31m¡ATENCIÓN! \033[1;33m¡ESTE SCRIPT HARÁ!\033[0m" # Translated "ATENCAO!" and "ESSE SCRIPT IRA !"
echo ""
echo -e "\033[1;31m• \033[1;33mINSTALAR UN CONJUNTO DE SCRIPTS COMO HERRAMIENTAS\033[0m" # Translated
echo -e "\033[1;33m  PARA LA GESTIÓN DE RED, SISTEMA Y USUARIOS\033[0m" # Translated
echo ""
echo -e "\033[1;32m• \033[1;32m¡CONSEJO! \033[1;33mUTILICE EL TEMA OSCURO EN SU TERMINAL PARA\033[0m" # Translated "DICA!" and "ULTILIZE..."
echo -e "\033[1;33m  UNA MEJOR EXPERIENCIA Y VISUALIZACIÓN DEL MISMO!\033[0m" # Translated "UMA MELHOR..." and fixed typo
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mEDIT:@gabrielitooss\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m" # Author tag, kept as is
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;36mGENERAR LAS CLAVES FREE [N/S]: \033[1;37m" # Translated "GENERAR AS KEY FREE"
read x
[[ $x = @(n|N) ]] && exit
echo -e "\033[1;36mSeleccione la Arquitectura de su VPS: \033[1;37m" # Translated "Selecione a Arquitetura da sua VPS:"
echo -e "[1] - x86_64" # Keep as is
echo -e "[2] - aarch64(ARM)" # Keep as is
echo -ne "\033[1;36mOpción: \033[1;37m" # Translated "Opção:"
read resposta
if [[ "$resposta" = '1' ]]; then
    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
    service ssh restart >/dev/null 2>&1
    mkdir /etc/rec >/dev/null 2>&1
    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m" # Translated "VERIFICANDO..."
    rm $_Ink/list >/dev/null 2>&1
    wget -P $_Ink https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/master/Install/list >/dev/null 2>&1
    verif_key
    sleep 3s
    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
    rm versao* >/dev/null 2>&1
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/master/Install/versao >/dev/null 2>&1
    >/dev/null 2>&1
    wget https://iplogger.org/2lHZ43 >/dev/null 2>&1
    >/dev/null 2>&1
    rm 2lHZ43 >/dev/null 2>&1
    cd /bin/ >/dev/null 2>&1
    rm v2raymanager >/dev/null 2>&1
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/main/Modulos/v2raymanager >/dev/null 2>&1
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/main/botteste.sh >/dev/null 2>&1
    chmod 777 v2raymanager >/dev/null 2>&1
    chmod 777 botteste.sh >/dev/null 2>&1
    mkdir $HOME/BOT >/dev/null 2>&1
    cd $HOME/BOT
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/master/Sistema/ShellBot.sh >/dev/null 2>&1
    chmod 777 ShellBot.sh >/dev/null 2>&1
    cd >/dev/null 2>&1
    #-----------------------------------------------------------------------------------------------------------------
    echo -e "\n\033[1;32m¡CLAVE VÁLIDA!\033[1;32m" # Translated "KEY VALIDA!"
    sleep 1s
    echo ""
    [[ -f "$HOME/usuarios.db" ]] && {
        clear
        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
        echo ""
        echo -e "                 \033[1;33m• \033[1;31mATENCIÓN \033[1;33m• \033[0m" # Translated "ATENCAO"
        echo ""
        echo -e "\033[1;33mUna base de Datos de Usuarios \033[1;32m(usuarios.db) \033[1;33m¡Fue" # Translated "Uma base de Dados..." and "Foi"
        echo -e "Encontrada! ¿Desea mantenerla preservando el límite" # Translated "Encontrada! Deseja mantê-la..."
        echo -e "de Conexiones simultáneas de los usuarios? ¿O Desea" # Translated "de Conexões simutaneas..." and "Ou Deseja" and fixed typo "simutaneas"
        echo -e "crear una nueva base de datos ?\033[0m" # Translated "criar uma nova base de dados ?"
        echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMantener Base de Datos Actual\033[0m" # Translated
        echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCrear una Nueva Base de Datos\033[0m" # Translated
        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
        echo ""
        tput setaf 2
        tput bold
        read -p "Opción ?: " -e -i 1 optiondb # Translated "Opção ?:"
        tput sgr0
    } || {
        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    }
    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    clear
    tput setaf 7
    tput setab 4
    tput bold
    printf '%35s%s%-18s\n' " ESPERE LA INSTALACIÓN" # Translated "AGUARDE A INSTALAÇÃO"
    tput sgr0
    echo ""
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mACTUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m" # Translated "ATUALIZANDO SISTEMA"
    echo ""
    echo -e "    \033[1;33m¡LAS ACTUALIZACIONES SUELEN TARDAR UN POCO!\033[0m" # Translated "ATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!"
    echo ""
    fun_attlist() {
        apt-get update -y
        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
        echo "crz: $(date)" >/usr/share/.plus/.plus
    }
    fun_bar 'fun_attlist'
    clear
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PAQUETES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m" # Translated "INSTALANDO PACOTES"
    echo ""
    echo -e "\033[1;33m¡ALGUNOS PAQUETES SON EXTREMADAMENTE NECESARIOS!\033[0m" # Translated "ALGUNS PACOTES SAO EXTREMAMENTE NECESSÁRIOS !"
    echo ""
    inst_pct() {
        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
        for _prog in ${_pacotes[@]}; do
            apt install $_prog -y
        done
        pip install speedtest-cli
    }
    fun_bar 'inst_pct'
    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
    ufw allow 80/tcp
    ufw allow 3128/tcp
    ufw allow 8799/tcp
    ufw allow 8080/tcp
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m" # Translated "FINALIZANDO"
    echo ""
    echo -e "      \033[1;33mOPTIMIZANDO PYTHON \033[0m" # Translated "OTIMIZANDO PYTHON"
    echo ""
    fun_bar 'otimize_python'
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m" # Translated "FINALIZANDO"
    echo ""
    echo -e "      \033[1;33m¡CONCLUYENDO FUNCIONES Y DEFINICIONES! \033[0m" # Translated "CONCLUINDO FUNÇÕES E DEFINIÇÕES!"
    echo ""
    fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
    clear
    echo ""
    cd $HOME
    echo -e "        \033[1;33m • \033[1;32mINSTALACIÓN CONCLUIDA\033[1;33m • \033[0m" # Translated "INSTALACAO CONCLUIDA" and fixed typo
    echo ""
    echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32mmenu\033[0m" # Translated "COMANDO PRINCIPAL:"
    echo -e "\033[1;33m MÁS INFORMACIÓN \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@SSHPLUS\033[0m" # Translated "MAIS INFORMACOES" and fixed typo. TELEGRAM kept as is.
    rm $HOME/Plus && cat /dev/null >~/.bash_history && history -c
elif [[ "$resposta" = '2' ]]; then
    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
    service ssh restart >/dev/null 2>&1
    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m" # Translated "VERIFICANDO..."
    rm $_Ink/listARM >/dev/null 2>&1
    wget -P $_Ink https://www.dropbox.com/s/cs5poyigwm97dyd/listARM >/dev/null 2>&1
    verif_key2
    sleep 3s
    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
    rm versao* >/dev/null 2>&1
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/master/Install/versao >/dev/null 2>&1
    >/dev/null 2>&1
    wget https://iplogger.org/2lHZ43 >/dev/null 2>&1
    >/dev/null 2>&1
    rm 2lHZ43 >/dev/null 2>&1
    cd /bin/ >/dev/null 2>&1
    rm v2raymanager >/dev/null 2>&1
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/main/Modulos/v2raymanager >/dev/null 2>&1
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/main/botteste.sh >/dev/null 2>&1
    chmod 777 v2raymanager >/dev/null 2>&1
    chmod 777 botteste.sh >/dev/null 2>&1
    mkdir $HOME/BOT >/dev/null 2>&1
    cd $HOME/BOT
    wget https://raw.githubusercontent.com/gabrielitooss/SSHPLUS/refs/heads/main/Sistema/ShellBot.sh >/dev/null 2>&1
    chmod 777 ShellBot.sh >/dev/null 2>&1
    cd >/dev/null 2>&1
    #-----------------------------------------------------------------------------------------------------------------
    echo -e "\n\033[1;32m¡CLAVE VÁLIDA!\033[1;32m" # Translated "KEY VALIDA!"
    sleep 1s
    echo ""
    [[ -f "$HOME/usuarios.db" ]] && {
        clear
        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
        echo ""
        echo -e "                 \033[1;33m• \033[1;31mATENCIÓN \033[1;33m• \033[0m" # Translated "ATENCAO"
        echo ""
        echo -e "\033[1;33mUna base de Datos de Usuarios \033[1;32m(usuarios.db) \033[1;33m¡Fue" # Translated "Uma base de Dados..." and "Foi"
        echo -e "Encontrada! ¿Desea mantenerla preservando el límite" # Translated "Encontrada! Deseja mantê-la..."
        echo -e "de Conexiones simultáneas de los usuarios? ¿O Desea" # Translated "de Conexões simutaneas..." and "Ou Deseja" and fixed typo "simutaneas"
        echo -e "crear una nueva base de datos ?\033[0m" # Translated "criar uma nova base de dados ?"
        echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMantener Base de Datos Actual\033[0m" # Translated
        echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCrear una Nueva Base de Datos\033[0m" # Translated
        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
        echo ""
        tput setaf 2
        tput bold
        read -p "Opción ?: " -e -i 1 optiondb # Translated "Opção ?:"
        tput sgr0
    } || {
        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    }
    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    clear
    tput setaf 7
    tput setab 4
    tput bold
    printf '%35s%s%-18s\n' " ESPERE LA INSTALACIÓN" # Translated "AGUARDE A INSTALAÇÃO"
    tput sgr0
    echo ""
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mACTUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m" # Translated "ATUALIZANDO SISTEMA"
    echo ""
    echo -e "    \033[1;33m¡LAS ACTUALIZACIONES SUELEN TARDAR UN POCO!\033[0m" # Translated "ATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!"
    echo ""
    fun_attlist() {
        apt-get update -y
        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
        echo "crz: $(date)" >/usr/share/.plus/.plus
    }
    fun_bar 'fun_attlist'
    clear
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PAQUETES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m" # Translated "INSTALANDO PACOTES"
    echo ""
    echo -e "\033[1;33m¡ALGUNOS PAQUETES SON EXTREMADAMENTE NECESARIOS!\033[0m" # Translated "ALGUNS PACOTES SAO EXTREMAMENTE NECESSÁRIOS !"
    echo ""
    inst_pct() {
        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
        for _prog in ${_pacotes[@]}; do
            apt install $_prog -y
        done
        pip install speedtest-cli
    }
    fun_bar 'inst_pct'
    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
    ufw allow 80/tcp
    ufw allow 3128/tcp
    ufw allow 8799/tcp
    ufw allow 8080/tcp
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m" # Translated "FINALIZANDO"
    echo ""
    echo -e "      \033[1;33mOPTIMIZANDO PYTHON \033[0m" # Translated "OTIMIZANDO PYTHON"
    echo ""
    fun_bar 'otimize_python'
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m" # Translated "FINALIZANDO"
    echo ""
    echo -e "      \033[1;33m¡CONCLUYENDO FUNCIONES Y DEFINICIONES! \033[0m" # Translated "CONCLUINDO FUNÇÕES E DEFINIÇÕES!"
    echo ""
    fun_bar "$_Ink/listARM $_lnk $_Ink $_1nk $key"
    clear
    echo ""
    cd $HOME
    echo -e "        \033[1;33m • \033[1;32mINSTALACIÓN CONCLUIDA\033[1;33m • \033[0m" # Translated "INSTALACAO CONCLUIDA" and fixed typo
    echo ""
    echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32mmenu\033[0m" # Translated "COMANDO PRINCIPAL:"
    echo -e "\033[1;33m MÁS INFORMACIÓN \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@SSHPLUS\033[0m" # Translated "MAIS INFORMACOES" and fixed typo. TELEGRAM kept as is.
    rm $HOME/Plus && cat /dev/null >~/.bash_history && history -c

else

    echo ""
    echo -e "\033[1;31m¡Opción inválida!\033[0m" # Translated "Opcao invalida !" and fixed typo
    sleep 1
    exit
fi
