#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mESPERE \033[1;37m- \033[1;33m[" # ESPERE - [

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mESPERE \033[1;37m- \033[1;33m[" # ESPERE - [

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}

echo " "

fun_atts () {

  [[ -e /home/versao ]] && rm /home/versao

  [[ -e /tmp/att ]] && rm /tmp/att

	wget -c -P /home https://raw.githubusercontent.com/kiritosshxd/SSHPLUS/master/Install/versao

	[[ -f "/home/versao" ]] && mv /home/versao /tmp/att

	[[ ! -e /bin/versao ]] && rm -rf /bin/menu

} > /dev/null 2>&1

echo -e "                              \033[1;31mPor kiritosshxd\033[1;36m" # By kiritosshxd

echo -e "   SSHPlus" | figlet

echo " "

echo -e "   \033[1;32mVERIFICANDO ACTUALIZACIONES DISPONIBLES\033[0m\n" # VERIFICANDO ACTUALIZACIONES DISPONIBLES

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

	echo -e "\n\033[1;31m ERROR AL CONECTAR AL SERVIDOR\n" # ERROR AL CONECTAR AL SERVIDOR

	echo -ne "\033[1;31m ENTER \033[1;33mpara regresar al \033[1;32mMENU!\033[0m"; read # ENTER para regresar al MENU!

	menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/versao| sed -e 's/[^0-9]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;36m     EL SCRIPT YA ESTÁ ACTUALIZADO!\033[1;32m\n" # EL SCRIPT YA ESTÁ ACTUALIZADO!

  rm /tmp/att > /dev/null 2>&1

  echo -e " \033[1;33m MÁS INFORMACIÓN \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@kiritosshxd\n" # MÁS INFORMACIÓN (TELEGRAM): EDIT:@kiritosshxd

  echo -ne " \033[1;31m ENTER \033[1;33mpara regresar al \033[1;32mMENU!\033[0m"; read # ENTER para regresar al MENU!

  menu

} || {

  echo -e "  \033[1;36m¡EXISTE UNA NUEVA ACTUALIZACIÓN DISPONIBLE!\033[1;33m\n" # ¡EXISTE UNA NUEVA ACTUALIZACIÓN DISPONIBLE!

  echo -e "  \033[1;33mMÁS INFORMACIÓN \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@kiritosshxd\n" # MÁS INFORMACIÓN (TELEGRAM): EDIT:@kiritosshxd

  echo -e "  \033[1;32mDETALLES DE LA ACTUALIZACIÓN:\033[0m\n" # DETALLES DE LA ACTUALIZACIÓN:

  while read linha; do

    echo -e "  \033[1;37m- \033[1;33m$linha"

  done < "/tmp/att"

  echo " "

  echo -ne "  \033[1;32m¿DESEA ACTUALIZAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read res # ¿DESEA ACTUALIZAR ? [s/n]:

  if [[ "$res" = s || "$res" = S ]];then

    echo -e "\n\033[1;32m  INICIANDO ACTUALIZACIÓN..." # INICIANDO ACTUALIZACIÓN...

    sleep 3

    wget https://raw.githubusercontent.com/kiritosshxd/SSHPLUS/master/Plus > /dev/null 2>&1

    chmod +x Plus

    ./Plus

    clear

    echo -e "\033[1;32mSCRIPT ACTUALIZADO CON ÉXITO\033[0m\n" # SCRIPT ACTUALIZADO CON ÉXITO

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;31mENTER \033[1;33mpara regresar al \033[1;32mMENU!\033[0m"; read # ENTER para regresar al MENU!

    menu

  else

    menu

  fi

}
